# Generated by Django 2.2.3 on 2019-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('temp', models.DecimalField(decimal_places=0, max_digits=3)),
                ('humd', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pres', models.DecimalField(decimal_places=0, max_digits=3)),
                ('wdir', models.DecimalField(decimal_places=0, max_digits=3)),
                ('wdsd', models.DecimalField(decimal_places=0, max_digits=3)),
                ('recordTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Weather',
            },
        ),
    ]
